version: '3.7'

services:
  appy_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: unless-stopped
    volumes: 
      - ./db/data:/var/lib/postgresql/data